### ISSUE TITLE
How to fix IPLUG15M in QXMLSERV type *N not found. error

### ISSUE THREAD

**Issue by owen-rpx** [IBM/xmlservice#48]
IPLUG15M in QXMLSERV type *N not found.

**Comment by jimoibm** [comment]
It works for me like below. Please check your stored procedure registration. Or you reinstall xmlservice as instructed in home page and retry.

`call qxmlserv.IPLUG15M('*NA', '*HERE', '<?xml version=''1.0''?> <sh>ps -ef</sh>', '?')`

**Comment by alanseiden** [comment]
@owen-rpx If you restored the QXMLSERV library from another system, the restoring may have occured in the wrong order.
Follow these steps:
1.  On the old system, re-save the library QXMLSERV to the save fil.e
2. On the new system, clear the QXMLSERV library, then restore it from the save file.

**Comment by kadler** [comment]
This can happen when restoring a PTF during an IPL, due to limitations in SQL processing when PTFs are applied. This should be resolved with PTF exits added since 2015 (going back to at least IBM i 7.3).

If for some reason you are still run into this issue, you can run the following command to create the stored procedures: `QSYS/CALL PGM(QHTTPSVR/QPZ1XS13)`
